name: '[DSP] Quality Engineering'

on:
  workflow_dispatch:
    inputs:
      cyRunnerBranch:
        description: 'Which branch to use on Cy-Runner?'
        default: 'main'

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@main
    with:
      cypress: true
      cyRunnerBranch: ${{ inputs.cyRunnerBranch }}
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      cypressJson: ${{ secrets.VTEX_QE }}
